spring.application.name=pedido
server.port=8086

spring.datasource.url=jdbc:mysql://localhost:3307/pedido_bd?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

microservices.cliente.url=http://localhost:8082/api/v1/clientes
microservices.sucursal.url=http://localhost:8083/api/v1/sucursales
microservices.pago.url=http://localhost:8087/api/v1/pagos
microservices.producto.url=http://localhost:8084/api/v1/productos
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
